### ISSUE TITLE
CUHKSZPASSPORT 疑似有个人信息 且 无法正常加载

### ISSUE THREAD

**Issue by yuantuo666** [Geraniol/geraniol.github.io#1]
在 `Data/Pages/CUHKSZPASSPORT/index.html` 文件中，提交至此地址 `/a/schl/inout/schlInoutStuMain/view?id=b1a7174ca5674173a6700d6f19119390` 的表单中存在时间和学院书院等数据。

另 `<script>` 写成了 `<scr1pt>` 导致网页无法使用。

**Comment by Geraniol** [comment]
感谢您非常专业的建议，目前我已把大部份标签的 `value` 替换掉了。
我在爬取网站的时候因数据较为杂乱没有注意到这个问题。
由于原始网页过于冗杂，在此基础上修改的脚本也过于混乱，我不得不考虑重新构建一个版本。

另外这里是故意将 `<script>` 写成 `<scr1pt>` 令网页无法使用。
因为有另一位程序员复制并且改进了这份代码，并建立了[专用存储库](https://DeliciousPancakes.github.io)，因此打算仅将此处代码作为备份。

再次感谢您的建议，我非常高兴有人能一起研究这些代码。
